### ISSUE TITLE
Helping in giving references

### ISSUE THREAD

**Issue by code-cop** [VedantKhairnar/Cheat-Sheets#1]
Hey! as you said you didn't give references as the resources are from **"variety"** of sources thought I should help you. So here is the resource the repo came from:

https://github.com/abhat222/Data-Science--Cheat-Sheet

Cheers 
Regards,
code-cop👮‍♂️

**Comment by VedantKhairnar** [comment]
Thanks  a lot!! I was searching this from a long time...I had to upload all these files to share with my friends, XD
Gracias!!
Stay Home, Stay Safe!!
