### ISSUE TITLE
Added more cheat sheets in web development resources

### ISSUE THREAD

**Issue by Ayush7614** [VedantKhairnar/Cheat-Sheets#101]
## 🚀 Feature

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...

**Describe the solution you'd like**
Added some more cheat sheets in web development resources

**Comment by Ayush7614** [comment]
Issue is under DWOC @VedantKhairnar sir plss assign me this issue

**Comment by Ayush7614** [comment]
@VedantKhairnar sir plss review it and assign me this issue

**Comment by VedantKhairnar** [comment]
No, thanks. I guess..we wont need it at moment.

**Comment by VedantKhairnar** [comment]
Can you specify what the cheatsheets are about precidely?

**Comment by Ayush7614** [comment]
Sir there is no Typescript Ecmascript BOOTSTRAP RUBY SCSS SASS and many more cheat sheets was not there so i have to work on this sir

**Comment by Ayush7614** [comment]
and plss sir also mentionong the level of issue and PR

**Comment by Ayush7614** [comment]
sir plss level the issue and review it

**Comment by Ayush7614** [comment]
For this issue #115 this is pull
