### ISSUE TITLE
VSCode and other Editors Cheatsheet #105

### ISSUE THREAD

**Issue by lokeshvenkatesan** [VedantKhairnar/Cheat-Sheets#105]
## 📚 Documentation
I wish to contribute to VSCode CheatSheet and 4 more PRs for code Editor Cheatsheet. Please assign me this issue. Do add Label DWOC.
Thank you
(A clear and concise description of what the issue is.)

## Have you spent some time to check if this issue has been raised before?

(Have you googled for a similar issue or checked our older issues for a similar bug)

**Comment by VedantKhairnar** [comment]
Pls proceed!
