### ISSUE TITLE
Add Cheat Sheets for Android

### ISSUE THREAD

**Issue by infiniteoverflow** [VedantKhairnar/Cheat-Sheets#110]
## 🚀 Feature

**Is your feature request related to a problem? Please describe.**
Cheat sheet section is not available for Android. 

**Describe the solution you'd like**
I would like to create a separate section for Android Development 

**Additional context**
I have been working on Android since some years , and i have gathered some good amount of resources that a beginner or an experienced person can use to refer.

**Comment by VedantKhairnar** [comment]
Pls proceed

**Comment by infiniteoverflow** [comment]
Done !!
