### ISSUE TITLE
Add a GitHub action to auto-assign Mentors for every PR

### ISSUE THREAD

**Issue by m-code12** [VedantKhairnar/Cheat-Sheets#124]
I would like to add a GitHub action to auto-assign mentors for every PR. It sometimes becomes hectic for the mentors to take a look at all the Projects for the PRs made by the Contributors. This action would give a nice notification about reviewing the pr and make things pretty easy for the mentor. It would automatically ask for reviews by the mentors on every pr created.

Demo :
<img src="https://user-images.githubusercontent.com/1641039/78471193-71573200-776a-11ea-9b40-810c2d63270e.png">

**Comment by m-code12** [comment]
@VedantKhairnar Can I implement this?

**Comment by VedantKhairnar** [comment]
I am the only maintainer here. So, will it be helpful actually?
Also, who these maintainers can be?

**Comment by m-code12** [comment]
> I am the only maintainer here. So, will it be helpful actually?
> Also, who these maintainers can be?

@VedantKhairnar 
Even if you are the only maintainer, you can make use of this action. This action will automatically ask for your reviewal whenever a new pr is opened.
These maintainers can be the members of your org, or the mentors for this project.

**Comment by VedantKhairnar** [comment]
It anyways asks when a new PR is opened and this is personal repo and at moment I am not looking forward in having any mentors, so might this isnt much needed at moment, I guess.

**Comment by m-code12** [comment]
> It anyways asks when a new PR is opened and this is personal repo and at moment I am not looking forward in having any mentors, so might this isnt much needed at moment, I guess.

Okay I am closing this issue then

**Comment by m-code12** [comment]
Also @VedantKhairnar, isn't the welcome bot on this repo working? , Can I raise an issue for that?
