### ISSUE TITLE
Adding Web Cheatsheets

### ISSUE THREAD

**Issue by pankaj892** [VedantKhairnar/Cheat-Sheets#27]
@VedantKhairnar  I would like to add cheatsheets regarding web development please assign me

**Comment by VedantKhairnar** [comment]
For contributing to DWOC,  list all those CheatSheets you are adding[Min 5]:

1) Cheat Sheet 1
2) Cheat Sheet 2
3) Cheat Sheet 3
4) Cheat Sheet 4
5) Cheat Sheet 5

Nt: Only 1 PR is accepted per person for DWOC

**Comment by pankaj892** [comment]
1.CheatsSheet for HTML
2.Cheatsheet for CSS
3.Cheatsheet for JS
4.Cheatsheet for Angular
5.Cheatsheet for Markdown
6.Cheatsheet for HTTP Status Codes 

Will that be Ok @VedantKhairnar

**Comment by VedantKhairnar** [comment]
Yes Pls Proceed
