### ISSUE TITLE
Adding wordpress cheat-sheet

### ISSUE THREAD

**Issue by Ak-panchal** [VedantKhairnar/Cheat-Sheets#28]
@VedantKhairnar I would like to add cheatsheets please assign me

**Comment by VedantKhairnar** [comment]
For contributing to DWOC,  list all those CheatSheets you are adding[Min 5]:

1) Cheat Sheet 1
2) Cheat Sheet 2
3) Cheat Sheet 3
4) Cheat Sheet 4
5) Cheat Sheet 5

Nt: Only 1 PR is accepted per person for DWOC
