### ISSUE TITLE
Add more files

### ISSUE THREAD

**Issue by VedantKhairnar** [VedantKhairnar/Cheat-Sheets#3]

**Comment by fcoterroba** [comment]
I can do this but need more info

**Comment by VedantKhairnar** [comment]
Add Files that come in the topics as per folder name, must be cheatsheets which are cool summary of that topic or must be a useful resource. Can also add files on new topics. @fcoterroba

**Comment by himanshu007-creator** [comment]
i sent a pull request regarding 30 DAYS OF PLACEMENT.

**Comment by Cruel-Crab** [comment]
I am interested in this issue;

**Comment by VedantKhairnar** [comment]
For contributing to DWOC,  list all those CheatSheets you are adding[Min 5]:

1) Cheat Sheet 1
2) Cheat Sheet 2
3) Cheat Sheet 3
4) Cheat Sheet 4
5) Cheat Sheet 5

Nt: Only 1 PR is accepted per person for DWOC
