### ISSUE TITLE
Website representation of this Repo with hyperlinks to the domains

### ISSUE THREAD

**Issue by VedantKhairnar** [VedantKhairnar/Cheat-Sheets#30]

**Comment by smriti1313** [comment]
Hi, do you mean to create a website of this "cheat-sheet" repository with hyperlinks to the folders present in it?

**Comment by sanjay270899** [comment]
I want to work on this.

**Comment by VedantKhairnar** [comment]
Yes, you got it right. Share a snap of frontend once you have made. You can work collaboratively as well.
Others interested in contributing can also work on the same.

**Comment by Sloth-Panda** [comment]
@VedantKhairnar Hey can I work on making this website collaboratively with @smriti1313 ?

**Comment by VedantKhairnar** [comment]
> @VedantKhairnar Hey can I work on making this website collaboratively with @smriti1313 ?

Yes, can you work using React js

**Comment by VedantKhairnar** [comment]
> Hi, do you mean to create a website of this "cheat-sheet" repository with hyperlinks to the folders present in it?
> Thank you

Can you work on React js for this?

**Comment by smriti1313** [comment]
@VedantKhairnar yeah i can surely do.  I and @Sloth-Panda would like to work on this website.

**Comment by VedantKhairnar** [comment]
Perfect!
@sanjay270899 has already started working. Pls collaborate. You can chat in the discord channel!

**Comment by smriti1313** [comment]
@VedantKhairnar 
I am extremely sorry but due to personal reasons I won't be able to do this website work. I request you to assign this work to someone else. I apologize again for the inconvenience caused.
Thank you.

**Comment by Sloth-Panda** [comment]
Hey, Can I do this using HTML, CSS, js?

**Comment by VedantKhairnar** [comment]
No worries @smriti1313 !
Hope you have a great winter at DWOC!
--------------------------------------------
@Sloth-Panda React has its own advantages over HTML and CSS. Also the work has started already so cant go with HTML CSS js. Sorry.

**Comment by Sloth-Panda** [comment]
Then I may take some time to do this  if you are okay but I can certainly do it

**Comment by VedantKhairnar** [comment]
Thanks Sanjay for your wonderful contribution!
