### ISSUE TITLE
CHEAT SHEET 01

### ISSUE THREAD

**Issue by Amit0412** [VedantKhairnar/Cheat-Sheets#31]
I WOULD LIKE TO SHARE THE CHEAT SHEET WHICH IS RELATED TO DATA ENGINEERING.
[8. Data Engineering.pdf](https://github.com/VedantKhairnar/Cheat-Sheets/files/5743531/8.Data.Engineering.pdf)

**Comment by VedantKhairnar** [comment]
For contributing to DWOC,  list all those CheatSheets you are adding[Min 5]:

1) Cheat Sheet 1
2) Cheat Sheet 2
3) Cheat Sheet 3
4) Cheat Sheet 4
5) Cheat Sheet 5

Nt: Only 1 PR is accepted per person for DWOC
