### ISSUE TITLE
CHEAT SHEET 02

### ISSUE THREAD

**Issue by Amit0412** [VedantKhairnar/Cheat-Sheets#32]
I WOULD LIKE TO ADD A CHEAT SHEET WHICH BASICALLY CONTAINS 100 NUMPY EXERCISES QUESTION.
[Python - 100 Numpy Exercises.pdf](https://github.com/VedantKhairnar/Cheat-Sheets/files/5743540/Python.-.100.Numpy.Exercises.pdf)

**Comment by VedantKhairnar** [comment]
For contributing to DWOC,  list all those CheatSheets you are adding[Min 5]:

1) Cheat Sheet 1
2) Cheat Sheet 2
3) Cheat Sheet 3
4) Cheat Sheet 4
5) Cheat Sheet 5

**Comment by Amit0412** [comment]
OHH YOU MEAN TO SAY THAT IN ONLY ONE ISSUE I LIST ALL THE CHEATSHEETS THAT I WANT TO ADD NOT INDIVISUAL.

**Comment by VedantKhairnar** [comment]
yess. exactly and you can add only once!
like only 1 contribution will be accepted for DWOC

**Comment by Amit0412** [comment]
OK.NOW I UNDERSTOOD COMPLETELY.WILL CONTRIBUTE TO TOMMOROW.THANKYOU

**Comment by VedantKhairnar** [comment]
Sure thanks!!

**Comment by Amit0412** [comment]
SIR I UPDATED AND SHARED 8 CHEAT SHEETS AS MUCH AS I HAVE.NOW WHAT'S NEXT
