### ISSUE TITLE
hii i would like to make a cheat sheet on nlp 

### ISSUE THREAD

**Issue by kenkirito** [VedantKhairnar/Cheat-Sheets#33]

**Comment by VedantKhairnar** [comment]
Sure  yes.
But for contributing to DWOC,  list all those CheatSheets you are adding[Min 5]:

1) Cheat Sheet 1
2) Cheat Sheet 2
3) Cheat Sheet 3
4) Cheat Sheet 4
5) Cheat Sheet 5

Nt: Only 1 PR is accepted per person for DWOC

**Comment by kenkirito** [comment]
ok understood thanks

**Comment by kenkirito** [comment]
can we share other people cheet sheet or we have to made our own cheat sheet

**Comment by VedantKhairnar** [comment]
Others are also welcome
