### ISSUE TITLE
I am adding cheatsheets for python,ML,DL and Data Science.Please check out.

### ISSUE THREAD

**Issue by Raghavi94** [VedantKhairnar/Cheat-Sheets#34]
1)Cheat Sheet 1-
[All in one cheatsheet(AI,ML,DL,BD).pdf](https://github.com/VedantKhairnar/Cheat-Sheets/files/5744559/All.in.one.cheatsheet.AI.ML.DL.BD.pdf)

2)Cheat Sheet 2-
[ML cheatsheet.pdf](https://github.com/VedantKhairnar/Cheat-Sheets/files/5744560/ML.cheatsheet.pdf)

3)Cheat Sheet 3-
[KB shortcuts for Data Scientist.pdf](https://github.com/VedantKhairnar/Cheat-Sheets/files/5744561/KB.shortcuts.for.Data.Scientist.pdf)

4)Cheat Sheet 4-
[sql joints cheatsheet.pdf](https://github.com/VedantKhairnar/Cheat-Sheets/files/5744563/sql.joints.cheatsheet.pdf)

5)Cheat Sheet 5-
[100 Python Interview ques with ans.pdf](https://github.com/VedantKhairnar/Cheat-Sheets/files/5744564/100.Python.Interview.ques.with.ans.pdf)

6)Cheat Sheet 6-
[Data Science cheatsheet.pdf](https://github.com/VedantKhairnar/Cheat-Sheets/files/5744565/Data.Science.cheatsheet.pdf)

7)Cheat Sheet 7-
[DS Interview ques.pdf](https://github.com/VedantKhairnar/Cheat-Sheets/files/5744575/DS.Interview.ques.pdf)

**Comment by VedantKhairnar** [comment]
Sure pls proceed

**Comment by Himanshi2016** [comment]
hey, can I do work on any one of the above mention cheat sheets ?
Actually , I want to work on cheat sheet 5, Thank you .

**Comment by VedantKhairnar** [comment]
@Himanshi2016  Raghavi is already adding them. You need to choose some new ones which arent there and quote them in a new issue.
