### ISSUE TITLE
Maintaining Cheat-sheets and documentation using Mdbook

### ISSUE THREAD

**Issue by arnabsen1729** [VedantKhairnar/Cheat-Sheets#35]
### Description
We can use something like [mdbooks](https://github.com/rust-lang/mdBook) or any other library to create a simple Markdown-based website.

**Features**
1. Since it supports Markdown we will have no difficulty in maintaining the website. Example of docs generated using mdbook is https://rust-lang.github.io/mdBook/
2. Even though the generated HTML, CSS files are very lightweight they have tons of feature like dark mode, light mode etc and also has search functionality which will play an important role from user accessibility pov.
3. We can easily deploy it to gh-pages and even use Travis CI or Github Actions to automate the build process.

**Comment by VedantKhairnar** [comment]
Yes we can proceed. Coool!
