### ISSUE TITLE
CHEAT SHEETS 

### ISSUE THREAD

**Issue by Amit0412** [VedantKhairnar/Cheat-Sheets#36]
A) CHEAT SHEET 1
[Python - 100 Numpy Exercises.pdf](https://github.com/VedantKhairnar/Cheat-Sheets/files/5744882/Python.-.100.Numpy.Exercises.pdf)

B) CHEAT SHEET 02
[CHEAT  VLC WINDOW.pdf](https://github.com/VedantKhairnar/Cheat-Sheets/files/5744883/CHEAT.VLC.WINDOW.pdf)

C) CHEAT SHEET 03
[njovin_sublime-text-2-windows.pdf](https://github.com/VedantKhairnar/Cheat-Sheets/files/5744884/njovin_sublime-text-2-windows.pdf)

D) CHEAT SHEET 04
[fredv_gmail.pdf](https://github.com/VedantKhairnar/Cheat-Sheets/files/5744887/fredv_gmail.pdf)

E) CHEAT SHEET 05
[jgebal_ruby-plsql-cheat-sheet.pdf](https://github.com/VedantKhairnar/Cheat-Sheets/files/5744890/jgebal_ruby-plsql-cheat-sheet.pdf)

F)CHEAT SHEET 06
[big-o-cheatsheet (3).pdf](https://github.com/VedantKhairnar/Cheat-Sheets/files/5744892/big-o-cheatsheet.3.pdf)

G)CHEAT SHEET 07
[PostgreSQL-Cheat-Sheet.pdf](https://github.com/VedantKhairnar/Cheat-Sheets/files/5744895/PostgreSQL-Cheat-Sheet.pdf)

**Comment by VedantKhairnar** [comment]
Pls proceed

**Comment by Amit0412** [comment]
NOW WHAT SHOULD I DO NEXT I MEAN FORK THIS ONE THEN UPDATE THE FORKED REPO BY ADDING ALL CHEASTSHEETS AND THEN CREATE PULL REQUEST.

**Comment by VedantKhairnar** [comment]
yess!
Exactly

**Comment by Harsh-bartariya** [comment]
sir i want to work on this issue and want to add some cheat sheats regarding remaining subjects and also existing ones so should i first mention about what will be added or first you assign me then i have to make a pull request. if this is the case kindly assign me this issue sir @VedantKhairnar

**Comment by vilsi12** [comment]
can i add for python

**Comment by VedantKhairnar** [comment]
@Harsh-bartariya its like, you can make your own issue with 5 PDFs min, will assign that to you
@vilsi12 yes pls
