### ISSUE TITLE
Cheat-sheets on javascripts

### ISSUE THREAD

**Issue by smriti1313** [VedantKhairnar/Cheat-Sheets#37]
1. Java fundamentals
[java-fundamentals](https://github.com/VedantKhairnar/Cheat-Sheets/files/5745117/sschaub_java-fundamentals.pdf)

2. C# naming conventions
[c-naming-conventions](https://github.com/VedantKhairnar/Cheat-Sheets/files/5745120/gregfinzer_c-naming-conventions.pdf)

3. Spring framework
[spring-framework-4](https://github.com/VedantKhairnar/Cheat-Sheets/files/5745122/danielfc_spring-framework-4.pdf)

4. Regular expression
[regular-expressions.pdf](https://github.com/VedantKhairnar/Cheat-Sheets/files/5745123/davechild_regular-expressions.pdf)

5. Pygame 
[Pygame](https://github.com/VedantKhairnar/Cheat-Sheets/files/5745116/PygameCheatSheet.pdf)

6. Angular js
[angularjs](https://github.com/VedantKhairnar/Cheat-Sheets/files/5745125/proloser_angularjs.pdf)

7. Vue.js
[vuex.pdf](https://github.com/VedantKhairnar/Cheat-Sheets/files/5745126/fortyseven_basic-vuex.pdf)

8. ember.js
[ember-js](https://github.com/VedantKhairnar/Cheat-Sheets/files/5745127/mwore_ember-js.pdf)

9. react.js
[reactjs.pdf](https://github.com/VedantKhairnar/Cheat-Sheets/files/5745128/kitallis_reactjs.pdf)

10. javascript
[javascript](https://github.com/VedantKhairnar/Cheat-Sheets/files/5745129/davechild_javascript.pdf)

**Comment by smriti1313** [comment]
While going through your repo, I could not see any "front-end" folder. So if the folder related to the files does not exist then am i allowed to create one?

**Comment by VedantKhairnar** [comment]
Yes you are

**Comment by Jassi10000** [comment]
I saw that many important cheatsheets are missing this list like Node.Js  , Express.Js ,MongoDB ,Gatsby and many others.
I would like to contribute in this  by putting these cheatsheets .Please assign me this issue to work on

**Comment by Cruel-Crab** [comment]
I am interested in this issue,
Kindly assign me,I have a good amount of JS cheatsheet images.
