### ISSUE TITLE
Add files on Competitive Programming

### ISSUE THREAD

**Issue by VedantKhairnar** [VedantKhairnar/Cheat-Sheets#4]

**Comment by fcoterroba** [comment]
I can do this but need more info

**Comment by Renu-code** [comment]
I can add different algorithms...can I work on this issue?

**Comment by ananya0504** [comment]
Hi, I can add various files on Competitive programming in C++, Java and Python. Please explain what kind of DS and Algorithms are preferred. Thanks!

**Comment by VedantKhairnar** [comment]
There's no constraints as such. All are welcome. Its better not to add codes say mergesort.py but cheatsheets which will clarify concepts
: D

**Comment by subhadeeppaul** [comment]
I can add some algorithms...

**Comment by VedantKhairnar** [comment]
Sure. If you want to contribute to some algorithm specific repo, you can contribute to [https://github.com/DevScript/CP-Solutions](https://github.com/DevScript/CP-Solutions)
Happy Coding!!

**Comment by ananya0504** [comment]
Hi can you pls explain what do you mean by not to add codes like mergesort.py?

**Comment by VedantKhairnar** [comment]
We dont want the separate files of codes. We need cheatsheets
