### ISSUE TITLE
Adding Cheat Sheet related to Version Control with Git & Github 

### ISSUE THREAD

**Issue by Himanshi2016** [VedantKhairnar/Cheat-Sheets#50]
I want to add a cheat sheet related to Git and Github . Can I proceed ?

**Comment by VedantKhairnar** [comment]
For contributing to DWOC, list all those CheatSheets you are adding[Min 5]:

Cheat Sheet 1
Cheat Sheet 2
Cheat Sheet 3
Cheat Sheet 4
Cheat Sheet 5
Nt: Only 1 PR is accepted per person for DWOC

**Comment by Himanshi2016** [comment]
This issue will include these Cheatsheets:
1. Version Control Cheatsheet.pdf
2. Git Cheatsheet.pdf
3. Github Cheatsheet.pdf
4. Command line.pdf
5.  Readme.md

**Comment by Himanshi2016** [comment]
Is this ok ?

**Comment by VedantKhairnar** [comment]
readme isnt a pdf, first 4 are cool

**Comment by Himanshi2016** [comment]
Sir , I have made a Pull request for this issue Version control with git & github and as a 5th pdf , I have added Git & Github cheatsheet. Please Check it.
Thank You !
