### ISSUE TITLE
Adding Tensorflow, Machine Learning and Deep Learning cheatsheets 

### ISSUE THREAD

**Issue by jsneha1710** [VedantKhairnar/Cheat-Sheets#54]
Tensorflow,ML and Deep Learning Cheatsheets

1.**Tensorflow** **Basics**
[Tensorflow Basics](http://www.aicheatsheets.com/static/pdfs/tensorflow_v_2.0.pdf)
2. **CS220 Deep Learning Cheatsheet**
[CS220 Stanford Deep learning Cheatsheet](https://github.com/afshinea/stanford-cs-229-machine-learning/blob/master/en/cheatsheet-deep-learning.pdf)
3.**AI,DL Complete Cheatsheet**
[The Complete AI, DL, ML, Big data Cheatsheet](https://www.dropbox.com/s/wmdguw5dfoaasuc/BecomingHumanCheatSheets.pdf?dl=0)
4.**Scikit Learn Cheatsheet**
[Scikit Learn Cheatsheet](https://www.analyticsvidhya.com/infographics/Scikit-Learn-Infographic.pdf)
5.**Data Visualisation in Python**
[Data Visualisation in Python](https://www.analyticsvidhya.com/blog/2015/06/data-visualization-in-python-cheat-sheet/)

**Comment by nitya123-github** [comment]
can i work on this issue for dwoc?

**Comment by VedantKhairnar** [comment]
@jsneha1710 pls make a pull request
If she doesnt reply soon, will assign it to you @nitya123-github
