### ISSUE TITLE
Adding cheat sheets for basic techniques used in data structures and algorithms questions

### ISSUE THREAD

**Issue by manvi0308** [VedantKhairnar/Cheat-Sheets#55]
**1. Make available all the tricks used commonly in DS-Algo questions one at a time**
**2. A cheat sheet cum resource pool for DS-Algo preparation**

**Comment by VedantKhairnar** [comment]
Pls proceed
Normally For contributing to DWOC, list all those CheatSheets you are adding[Min 5]:

Cheat Sheet 1
Cheat Sheet 2
Cheat Sheet 3
Cheat Sheet 4
Cheat Sheet 5
Nt: Only 1 PR is accepted per person for DWOC

If the content is rich, we can proceed with this this as well.

**Comment by manvi0308** [comment]
Cheat Sheet1 : Arrays
Cheat Sheet 2: Bit Manipulation
Cheat Sheet 3:  Mathematics Based questions

Is this fine?

**Comment by VedantKhairnar** [comment]
For DWOC, will need minimum 3
else in general, this works!

**Comment by manvi0308** [comment]
Ok
