### ISSUE TITLE
PHP , JS ,  jQuery , CNN , Probability 

### ISSUE THREAD

**Issue by akrish4** [VedantKhairnar/Cheat-Sheets#57]
Hi @VedantKhairnar 
I woul like to add these cheatsheets 
1. CHEATSHEET 1 : [probabailty.pdf](https://github.com/VedantKhairnar/Cheat-Sheets/files/5753957/probabailty.pdf)
2. CHEATSHEET 2: [CNN.pdf](https://github.com/VedantKhairnar/Cheat-Sheets/files/5753985/CNN.pdf)
3. CHEATSHEET 3:  [php-cheatsheet.pdf](https://github.com/VedantKhairnar/Cheat-Sheets/files/5753987/php-cheatsheet.pdf)
4. CHEATSHEET 4:  [javascript-full-cheatsheet.pdf](https://github.com/VedantKhairnar/Cheat-Sheets/files/5753988/javascript-full-cheatsheet.pdf)
5. CHEATSHEET 5:  [jQuery.pdf](https://github.com/VedantKhairnar/Cheat-Sheets/files/5753989/jQuery.pdf)
Kindly assign me 
(DWOC)

**Comment by akrish4** [comment]
kindly add the level labels also 
@VedantKhairnar

**Comment by VedantKhairnar** [comment]
Pls proceed

**Comment by akrish4** [comment]
@VedantKhairnar Can you tell me which folder should i add `jquery` and `php` cheatsheets ? no folder for them

**Comment by VedantKhairnar** [comment]
jquery in web and for php make a new folder
