### ISSUE TITLE
Regex and google cloud developer cheat sheets

### ISSUE THREAD

**Issue by sakshikhachane** [VedantKhairnar/Cheat-Sheets#58]
1. Java Regex Cheat Sheet
2. Python Regex Cheat Sheet
3. JavaScript regex Cheat Sheet
4. Google Cloud Developer Cheat Sheet
5. MongoDB Cheat Sheet

@VedantKhairnar Please assign me this issue. I am a participant in DWOC.

**Comment by VedantKhairnar** [comment]
Pls proceed.

**Comment by sakshikhachane** [comment]
@VedantKhairnar Please add the level to this else won't get counted.
