### ISSUE TITLE
Django cheatsheet

### ISSUE THREAD

**Issue by djm-1** [VedantKhairnar/Cheat-Sheets#60]
Django is a popular web framework in python. I have done many projects using it. I want to contribute a cheatsheet on Django which will be very much helpful for backend developers. Please assign me the task for DWoC.

**Comment by VedantKhairnar** [comment]
Bro, for contributing to DWOC, list all those CheatSheets you are adding[Min 5]:

Cheat Sheet 1
Cheat Sheet 2
Cheat Sheet 3
Cheat Sheet 4
Cheat Sheet 5
Nt: Only 1 PR is accepted per person for DWOC

All cheatsheets shouldnt necessarily be for 1 tech

**Comment by djm-1** [comment]
Ok

**Comment by djm-1** [comment]
### Django Cheatsheets
1. beginners_python_cheat_sheet_pcc_django.pdf
2. django095-cheat-sheet.pdf
3. django_reference_sheet.pdf
4. lewiseason_django-models.pdf
5. simplecheatsheet-com-tag-django-cheat-sheet-.pdf

Kindly check my PR. Thank you.
