### ISSUE TITLE
Python Cheatsheets

### ISSUE THREAD

**Issue by vaishnavirshah** [VedantKhairnar/Cheat-Sheets#64]
1. Collections Module - Counter, default dict, named tuple.
2. Datetime Module
3. Math and Random Modules
4. Regex Expression
5. Images
6. Sending emails with Python

@VedantKhairnar I am a participant in DWOC, I would like to contribute to this issue. Could you assign it to me?

**Comment by VedantKhairnar** [comment]
pls proceed
