### ISSUE TITLE
Data science, Pytorch, Keras, Numpy, Java Multi threading, Swing/ AWT Cheat-sheets

### ISSUE THREAD

**Issue by madhurima99** [VedantKhairnar/Cheat-Sheets#68]
1. Intro to Pytorch cheatsheet
2. Keras cheatsheet
3. Python Numpy cheatsheet
4. Data science interview questions
5. Java Multithreading cheatsheet
6. Swing/AWT cheatsheet

@VedantKhairnar  I am a participant in DWOC, I would like to add those following cheatsheets. 
This is my first issue, could you assign this to me?

**Comment by VedantKhairnar** [comment]
Pls proceed
