### ISSUE TITLE
Hey, can I add html, css cheatsheets?

### ISSUE THREAD

**Issue by Sloth-Panda** [VedantKhairnar/Cheat-Sheets#73]

**Comment by VedantKhairnar** [comment]
For contributing to DWOC, list all those CheatSheets you are adding[Min 5]:

Cheat Sheet 1
Cheat Sheet 2
Cheat Sheet 3
Cheat Sheet 4
Cheat Sheet 5
Nt: Only 1 PR is accepted per person for DWOC

**Comment by Sloth-Panda** [comment]
Hey would also like to add some other cheatsheets basically on sass, less and topics like that

**Comment by Sloth-Panda** [comment]
1. HTML cheat sheet
2. CSS cheat sheet
3. BOOTSTRAP cheat sheet
4.  SASS cheat sheet
5.  NODE cheat sheet
