### ISSUE TITLE
Integrate Welcome Bot

### ISSUE THREAD

**Issue by tharunc** [VedantKhairnar/Cheat-Sheets#74]
Hello there,
         I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time as a part of DWOC. Please assign me this issue. For reference, kindly check out: https://github.com/apps/welcome
THANK YOU

**Comment by VedantKhairnar** [comment]
Sure!
Give some cool wlcm msg if possible with steps and conditions. Let me know if you dont know the condition of min 5 Cheat sheets.
Will explain.

**Comment by tharunc** [comment]
Please add DWOC tag.
