### ISSUE TITLE
Compressing the cheatsheets size maybe using some zipper

### ISSUE THREAD

**Issue by Sloth-Panda** [VedantKhairnar/Cheat-Sheets#78]
It takes a lot of time to clone the repo to a local machine to start working on it so maybe making the files sizes smaller by zipping may help

doubt-> can we put all the files under a single zipped file??

**Comment by VedantKhairnar** [comment]
I totally agree to your point, but we wont be able to access them in github web when they are zipped rt?
Can we have some solution on this?

**Comment by Sloth-Panda** [comment]
Yes, that was my doubt too. I will research a bit on it and will let you know

**Comment by VedantKhairnar** [comment]
Sure yeaah
