### ISSUE TITLE
Add Contributors Table in README.md

### ISSUE THREAD

**Issue by samir-0711** [VedantKhairnar/Cheat-Sheets#88]
## 📚 Documentation

To make README.md file beautiful and give credit to contributors
Like this
![image](https://user-images.githubusercontent.com/68433936/104681949-8c9f9680-5719-11eb-8dba-ca8b69c53ecd.png)

## Have you spent some time to check if this issue has been raised before?

Yes

**Comment by samir-0711** [comment]
I would like to work on this.

**Comment by VedantKhairnar** [comment]
Pls proceed

**Comment by samir-0711** [comment]
Sorry for the inconvenience @VedantKhairnar 
Link updated.
Thank You.
