### ISSUE TITLE
Add a contributors table in readme

### ISSUE THREAD

**Issue by shatakshisingh24** [VedantKhairnar/Cheat-Sheets#92]
Hii! I can add a contributor's table in Readme file, like this one.

![image](https://user-images.githubusercontent.com/51313537/104820300-dabbb380-5859-11eb-9114-6fb883849d86.png)

Kindly assign me this issue, with label DWOC and Level-1 or 2

**Comment by VedantKhairnar** [comment]
Yeaah pls proceed

**Comment by VedantKhairnar** [comment]
Sorry to say but someone is already working on this
Will assign you of that person doesnt revert back soon.

**Comment by shatakshisingh24** [comment]
Sure

**Comment by Amit366** [comment]
Can I contribute to this issue??
