### ISSUE TITLE
I would like to add the Cheat-Sheets for CSS

### ISSUE THREAD

**Issue by codiiyapaa** [VedantKhairnar/Cheat-Sheets#94]
## 🚀 CSS Cheat-Sheets

Concise cheat-Sheets for CSS covering almost everything.

![CSS-CheatSheet-1](https://user-images.githubusercontent.com/67871592/104975361-7c8cfd00-5a20-11eb-8a19-117c9e0484f0.png)
![CSS-CheatSheet-2](https://user-images.githubusercontent.com/67871592/104975386-89115580-5a20-11eb-808f-eb22d2a5121d.png)
![CSS-CheatSheet-3](https://user-images.githubusercontent.com/67871592/104975402-8f073680-5a20-11eb-90f7-d5087afd5ed2.png)
![CSS-CheatSheet-4](https://user-images.githubusercontent.com/67871592/104975428-9b8b8f00-5a20-11eb-9211-8990255fe701.png)

**Comment by VedantKhairnar** [comment]
This is amazing! Go on.
Is this for DWOC?

**Comment by codiiyapaa** [comment]
Nopes! Just General Contribution.

**Comment by VedantKhairnar** [comment]
Cool! 
You can proceed by making a PR! ❄️
