### ISSUE TITLE
Ruby cheatsheet

### ISSUE THREAD

**Issue by anushkasinghal11** [VedantKhairnar/Cheat-Sheets#95]
## 📚 Documentation

(A clear and concise description of what the issue is.)
I would like to add a cheatsheet for Ruby. I want to work on this under DWoC'21
## Have you spent some time to check if this issue has been raised before?
(Have you googled for a similar issue or checked our older issues for a similar bug)

**Comment by VedantKhairnar** [comment]
For DWOC, we need min 5 cheatsheets

**Comment by VedantKhairnar** [comment]
Will be closed by tomorrow if no response is received!
